### ISSUE TITLE
Upgrade Microsoft.IdentityModel.Protocols.OpenIdConnect to v7

### ISSUE THREAD

**Issue by acn-sbuad** [Altinn/altinn-accesstoken#50]
### Description

During routine patching to v7 testing was not successful. 
It was tested with Platform Events. 

When upgrading extensive testing is to be expected. 

Tested referencing the upgraded AccesstokenClient project. Error logged in events was `There should be one accesss token`

**Comment by acn-sbuad** [comment]
HAs been upgraded in accesstoken, only accesstokenclient remaining

**Comment by SandGrainOne** [comment]
Tested okay through use of the new package in Events
